"""Content templates for the files generated by the `new` command.

These templates intentionally follow the CLI spec (Part 4 / Part 5):
- Solution.java: minimal, no unnecessary comments.
- notes.md: standard revision sections.
"""

from __future__ import annotations


def solution_template() -> str:
    """Minimal Java solution template."""
    return """\
import java.util.*;

public class Solution {

    public static void main(String[] args) {

    }

}
"""


def notes_template() -> str:
    """Standard revision notes template with empty sections."""
    return """\
# Approach

-

# Observations

-

# Mistakes

-

# Better Solution

-

# Revision Notes

-
"""


def metadata_template(
    title: str,
    slug: str,
    topic: str,
    source: str,
    status: str,
    language: str,
    difficulty: str,
    created: str,
) -> str:
    """Metadata JSON following the CLI spec (Part 3)."""
    # JSON-safe double quotes in title.
    safe_title = title.replace("\\", "\\\\").replace('"', '\\"')

    return f"""\
{{
  "title": "{safe_title}",
  "slug": "{slug}",
  "topic": "{topic}",
  "source": "{source}",
  "difficulty": "{difficulty}",
  "status": "{status}",
  "language": "{language}",
  "created": "{created}",
  "solved": null,
  "tags": [],
  "time_complexity": "",
  "space_complexity": ""
}}
"""